export const types = {
  INCREASE: 'INCREASE',
  DECREASE: 'DECREASE',
  PTTID: 'PTTID',
  ALERT: 'Alert',
  CLEARALERT: 'CLEARALERT',
  ADDANYSEARCH: 'ADDANYSEARCH',
  SETNEWCOMMENT: 'SETNEWCOMMENT',
  GOTOPOST: 'GOTOPOST',
  COMMENTDATA: 'CommentData',
  UPDATEBOARD: 'updateBoard',
  UPDATEPOST: 'UpdatePost',
  UPDATECHAT: 'Updatechatlist',
  CLEARCHAT: 'CLEARCHAT',
  SETPOSTLASTENDLINE: 'SETPOSTLASTENDLINE',
  SETPOSTCOMMENTCOUNT: 'SETPOSTCOMMENTCOUNT',
  UPDATELOG: 'UpdateLog',
  REMOVELOG: 'RemoveLog',
  VIDEOSTARTDATE: 'VIDEOSTARTDATE',
  VIDEOPLAYEDTIME: 'VIDEOPLAYEDTIME',
  VIDEOCURRENTRIME: 'VIDEOCURRENTRIME',
  PAGECHANGE: 'PAGECHANGE',
  GOTOCHAT: 'GOTOCHAT',
  PTTSTATE: 'PTTSTATE',
  ISSTREAM: 'ISSTREAM',
  PREVIEWIMG: 'PREVIEWIMG',
  REINSTANCEPTT: 'REINSTANCEPTT',
  CUSTOMPLUGINSETTING: 'menuCommand-customPluginSetting-',
  SITENAME: 'siteName',

  // checkbox
  ENABLESETNEWCOMMENT: 'EnableSetNewComment',
  DISABLECOMMENTGRAY: 'DisableCommentGray',
  DELETEOTHERCONNECT: 'DeleteOtherConnect',
  ANYSEARCHHINT: 'ANYSEARCHHINT',

  // input value
  PLUGINHEIGHT: 'PluginHeight',
  CHATFONTSIZE: 'Fontsize',
  CHATSPACE: 'ChatSpace',
  COMMENTINTERVAL: 'CommentInterval',
  PLUGINWIDTH: 'PluginWidth',
  PLUGINPORTRAITHEIGHT: 'PluginPortraitHeight',

  // inputfield value
  ENABLEBLACKLIST: 'EnableBlacklist',
  BLACKLIST: 'Blacklist',
  ENABLECOMMENTBLACKLIST: 'EnableCommentBlacklist',
  COMMENTBLACKLIST: 'CommentBlacklist',

  // dropdown
  THEME: 'Theme',
  THEMECOLORBG: 'ThemeColorBG',
  THEMECOLORBORDER: 'ThemeColorBorder',
  TITLELIST: 'TitleList'
}
